### ISSUE TITLE
When wrapping the UseAnimation component to give it an onClick function, the animation fails to play in reverse.

### ISSUE THREAD

**Issue by gapark** [useAnimations/react-useanimations#6]
I am unsure if this is an issue but I cannot find a way around it. I have tried to wrap my UseAnimation component inside a button to give it an onClick function, as I cannot seem to assign one in another way. When I do this, the animation fails to play in reverse. 

```
const getClickAndPlayBackwardsEvents = animation => {
  let directionMenu = 1;
  return {
    onClick: () => {
      animation.setDirection(directionMenu);
      animation.play();
      directionMenu = -directionMenu;
    },
  };
};
```
Logging `directionMenu` from the above function in `getEvent.js` shows it remains as 1 regardless of the numbers of times clicked. 

When not wrapped in another component, the animation works perfectly.

**Comment by tuanphungcz** [comment]
So I've tried to simulate your use case and so far I'm not able to reproduce the bug. 

👉 https://codesandbox.io/s/restless-glitter-cocvi
Could you show me the bug in the code sandbox? @gapark

**Comment by gapark** [comment]
@digilifecz123 

~~I think it's worth mentioning that I am using the [material-ui library](https://material-ui.com/), however, as can be seen[ in the sandbox](https://codesandbox.io/s/laughing-goldstine-rzzch?fontsize=14), neither the standard button component, nor the IconButton component from material-ui work with the animated icon.~~

~~Curiously, the material-ui Button component works with the icons, also shown in the sandbox.~~

It seems to be the function I am initiating on click that stops the icon from animating, not the component itself. When I change the function to a console.log() it all works.

I have updated [the sandbox](https://codesandbox.io/s/laughing-goldstine-rzzch?fontsize=14) with examples of working and non working buttons

**Comment by tsujp** [comment]
Using onClick is completely breaking reverse animations for me also, but only if wrapped. I tried a `button` and a `div`, both break it.

If I use the exact same onClick directly on the `UseAnimations` component it works fine.

**Comment by komardev** [comment]
> 
> 
> @digilifecz123
> 
> ~I think it's worth mentioning that I am using the [material-ui library](https://material-ui.com/), however, as can be seen[ in the sandbox](https://codesandbox.io/s/laughing-goldstine-rzzch?fontsize=14), neither the standard button component, nor the IconButton component from material-ui work with the animated icon.~
> 
> ~Curiously, the material-ui Button component works with the icons, also shown in the sandbox.~
> 
> It seems to be the function I am initiating on click that stops the icon from animating, not the component itself. When I change the function to a console.log() it all works.
> 
> I have updated [the sandbox](https://codesandbox.io/s/laughing-goldstine-rzzch?fontsize=14) with examples of working and non working buttons

the icon cant back to normal when i click for the second time

**Comment by tsujp** [comment]
@digilifecz123 any chance of a patch? I'm unsure what's causing this.

**Comment by tsujp** [comment]
@digilifecz123 here is a demo of the bug: https://codesandbox.io/s/reverent-tesla-x6psw

**Comment by ben-cart3r** [comment]
I believe this is caused by calling "getEvents" in the render method. A change to the state of a wrapper component will cause the render method to be called again and the events re-created and directionMenu will always equal 1.

Are you happy to accept a PR to fix this? @digilifecz123

**Comment by dyontaistaton** [comment]
I Fixed It But I'm New To Github, Give me a sec to figure out out to upload it to the package 👍 
`
var getClickAndPlayBackwardsEvents=function getClickAndPlayBackwardsEvents(animation) {
  return {
    onClick: function onClick() {
      console.log(animation);
      if(animation.currentFrame==0) {
        animation.play();
        animation.setDirection(1);
      }
      else {
        animation.setDirection(animation.playDirection*-1);
        animation.play();
      }
    }
  };
};
`
update this function in getEvents.js

**Comment by dyontaistaton** [comment]
> I Fixed It But I'm New To Github, Give me a sec to figure out out to upload it to the package 👍
> `var getClickAndPlayBackwardsEvents=function getClickAndPlayBackwardsEvents(animation) { return { onClick: function onClick() { console.log(animation); if(animation.currentFrame==0) { animation.play(); animation.setDirection(1); } else { animation.setDirection(animation.playDirection*-1); animation.play(); } } }; };`
> update this function in getEvents.js

Alright I Uploaded The Fixed Pull Request, also I forked it, as dyontaistaton/react-useanimations

**Comment by ghost** [comment]
Any updates?

**Comment by marekfeikus** [comment]
@mjfneto @dyontaistaton @gapark @tsujp @komarudinn  I've implemented it today - this is how you can use it from now.
```
export const WrapperElement = () => {
  return (
    <UseAnimation
      animation={heart}
      size={60}
      onClick={() => {
        console.log('additional onClick cb is working');
      }}
      render={(eventProps, animationProps) => (
        <button style={{ padding: '20px' }} type="button" {...eventProps}>
          <div {...animationProps} />
        </button>
      )}
    />
  );
};
```
You can also check it live in our [Storybook](https://useanimations.github.io/react-useanimations/?path=/story/variants--wrapper-element) Check the README for more info.

**Comment by fajoaq** [comment]
In case anyone is still having issue like I was, I found that my problem was React updating the component before it could fire off the reverse animation. I tried everything, including use of PureComponent. 
In the end what worked was using a Ref in conjunction with state to update my HOC, I guess it gave the animation enough time to fire before props were updated. Cheers.

```
  const menuOpenRef = useRef(false);
  const [menuOpen, setMenuOpen] = useState(false);

  const handleBurgerClick = () => {
    if (menuOpenRef.current) {
      setMenuOpen(!menuOpenRef.current);
      menuOpenRef.current = !menuOpenRef.current;
    } else {
      menuOpenRef.current = true;
      setMenuOpen(true);
    }
  };
```

**Comment by fajoaq** [comment]
If anyone is still having issues like I was, my solution was to make the wrapper element a PureComponent, as well as moving all prop updates to the HOC. Lastly, I needed to use a ref in conjunction with useState, I guess to give the reverse animation sufficient time to fire off before getting re-rendered?
eg.
```

 // Wrapper Element
  class Burger extends PureComponent {
    <UseAnimation
    ...
    />
  }

//HOC
  const menuOpenRef = useRef(false);
  const [menuOpen, setMenuOpen] = useState(false);

  const handleBurgerClick = () => {
    if (menuOpenRef.current) {
      setMenuOpen(!menuOpenRef.current);
      menuOpenRef.current = !menuOpenRef.current;
    } else {
      menuOpenRef.current = true;
      setMenuOpen(true);
    }
  };
```
